<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'full name'                                                   => 'ПІБ',
    'email'                                                       => 'Електронна пошта',
    'phone'                                                       => 'Номер телефона',
    'address'                                                     => 'Адрес',
    'save changes'                                                => 'Зберегти зміни',
    'sign in'                                                     => 'Увійти',
    'username'                                                    => 'Ім\'я користувача',
    'password'                                                    => 'Пароль',
    'rememberMe'                                                  => 'Запам\'ятати',
    'login'                                                       => 'Логін',
    'If you forgot your password you can'                         => 'Якщо Ви забули пароль, Ви можете',
    'reset it'                                                    => 'відновити його',
    'For new user you can'                                        => 'Для нових користувачів доступна',
    'sign up'                                                     => 'Реєстрація',
    'Change Password'                                             => 'Змінити пароль',
    'Please fill out the following fields to change password:'    => 'Будь ласка, заповніть такі поля щоб змінити пароль:',
    'old Password'                                                => 'Старий пароль',
    'new Password'                                                => 'Новий пароль',
    'retype Password'                                             => 'Повторіть пароль',
    'Change'                                                      => 'Змінити',
    'Request password reset'                                      => 'Запит відновлення пароля',
    'Send'                                                        => 'Відправити',
    'Reset password'                                              => 'Відновити пароль',
    'Save'                                                        => 'Зберегти',
    'Please choose your new password:'                            => 'Будь ласка, ведіть новий пароль:',
    'Create account'                                              => 'Створити аккаунт',
    'Users'                                                       => 'Користувачі',
];
