<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'full name'                                                   => 'ФИО',
    'email'                                                       => 'Электронная почта',
    'phone'                                                       => 'Номер телефона',
    'address'                                                     => 'Адрес',
    'save changes'                                                => 'Сохранить изменения',
    'sign in'                                                     => 'Войти',
    'username'                                                    => 'Имя пользователя',
    'password'                                                    => 'Пароль',
    'rememberMe'                                                  => 'Запомнить',
    'login'                                                       => 'Логин',
    'If you forgot your password you can'                         => 'Если Вы забыли пароль, Вы можете',
    'reset it'                                                    => 'сбросить его',
    'For new user you can'                                        => 'Для новых пользователей доступна',
    'sign up'                                                     => 'регистрация',
    'Change Password'                                             => 'Поменять пароль',
    'Please fill out the following fields to change password:'    => 'Пожалуйста, заполните следующие поля что бы поменять пароль:',
    'old Password'                                                => 'Старый пароль',
    'new Password'                                                => 'Новый пароль',
    'retype Password'                                             => 'Повторите пароль',
    'Change'                                                      => 'Изменить',
    'Request password reset'                                      => 'Запрос сброса пароля',
    'Send'                                                        => 'Отправить',
    'Reset password'                                              => 'Сбросить пароль',
    'Save'                                                        => 'Сохранить',
    'Please choose your new password:'                            => 'Пожалуйста, введите новый пароль:',
    'Create account'                                              => 'Создать аккаунт',
    'Users'                                                       => 'Пользователи',
];
