<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID'                                                  => 'ІД',
    'Content'                                             => 'Коментар',
    'Entity'                                              => 'Модель',
    'Entity ID'                                           => 'ІД моделі',
    'Parent ID'                                           => 'Наслідування',
    'Status'                                              => 'Статус',
    'Level'                                               => 'Рівень',
    'Created by'                                          => 'Створений',
    'Updated by'                                          => 'Оновлений',
    'Related to'                                          => 'Відноситься до',
    'Url'                                                 => 'Урл',
    'Created date'                                        => 'Дата створення',
    'Updated date'                                        => 'Дата оновлення',
    'View'                                                => 'Перегляд',
    'Update'                                              => 'Оновити',
    'Delete'                                              => 'Видалити',
    'Reply'                                               => 'Відповісти',
    'Comments ({0})'                                      => 'Коментарі ({0})',
    'Comment cannot be blank.'                            => 'Коментар не може бути порожнім.',
    'Comment has not been deleted. Please try again!'     => 'Не вдалось видалити коментар. Спробуйте будь ласка ще раз.',
    'Add a comment...'                                    => 'Додати коментар ...',
    'Comment'                                             => 'Опублікувати коментар',
    'Oops, something went wrong. Please try again later.' => 'Не вдалось додати коментар. Спробуйте будь ласка ще раз.',
    'The requested page does not exist.'                  => 'Помилка 404 - сторінка не знайдена!',
    'Comment has been deleted.'                           => 'Коментар видалено.',
    'Comment has been saved.'                             => 'Коментар збережено.',
    'Click here to cancel reply.'                         => 'Нажміть тут, щоб відмінити відповідь.',
    'Comments Management'                                 => 'керування Коментарями',
    'Select Status'                                       => 'Виберіть Статус',
    'Select Author'                                       => 'Виберіть Автора',
    'Update Comment: {0}'                                 => 'Оновити коментар: {0}',
    'Active'                                              => 'Активний',
    'Deleted'                                             => 'Видалений',
    'Go Back'                                             => 'Повернутись',
    'No comments found'                                   => 'Будьте першими, хто залишить коментар.',
    'sign up'                                             => 'Будь ласка, авторизуйтесь, щоб залишити коментар',

];
