<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new Products'        => 'Добавить новый товар',
    'Edit categories'         => 'Редактировать категории',
    'Photo'                   => 'Фото',
    'Name'                    => 'Наименование',
    'Category name'           => 'Категория',
    'Please select'           => 'Пожалуйста, выбирите',
    'Search'                  => 'Поиск',

    'Name in Ukrainian'         => 'Наименование на украинском',
    'Name in Russian'           => 'Наименование на руском',
    'Name in English'           => 'Наименование на английскос',
    'Description in Ukrainian'  => 'Описание на украинском',
    'Description in Russian'    => 'Описание на руском',
    'Description in English'    => 'Описание на английскос',
    'Price'                     => 'Цена',
    'Add'                       => 'Добавить',
    'Update'                    => 'Обновить',

    'Add new Category'          => 'Добавить новую категорию',
    'Edit products'             => 'Управление товаром',

];
