<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new Products'          => 'Add new Products',
    'Edit categories'           => 'Edit categories',
    'Photo'                     => 'Photo',
    'Name'                      => 'Name',
    'Category name'             => 'Category name',
    'Please select'             => 'Please select',
    'Search'                    => 'Search',

    'Name in Ukrainian'         => 'Name in Ukrainian',
    'Name in Russian'           => 'Name in Russian',
    'Name in English'           => 'Name in English',
    'Description in Ukrainian'  => 'Description in Ukrainian',
    'Description in Russian'    => 'Description in Russian',
    'Description in English'    => 'Description in English',
    'Price'                     => 'Price',
    'Add'                       => 'Add',
    'Update'                    => 'Update',

    'Add new Category'          => 'Add new Category',
    'Edit products'             => 'Edit products',


];
