<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add new Products'        => 'Додати новий товар',
    'Edit categories'         => 'Редагувати категорії',
    'Photo'                   => 'Фото',
    'Name'                    => 'Назва',
    'Category name'           => 'Категорія',
    'Please select'           => 'Будь ласка, виберіть',
    'Search'                  => 'Пошук',

    'Name in Ukrainian'         => 'Назва українською',
    'Name in Russian'           => 'Назва російською',
    'Name in English'           => 'Назва англійською',
    'Description in Ukrainian'  => 'Опис українською',
    'Description in Russian'    => 'Опис російською',
    'Description in English'    => 'Опис англійською',
    'Price'                     => 'Вартість',
    'Add'                       => 'Додати',
    'Update'                    => 'Оновити',

    'Add new Category'          => 'Додати нову категорію',
    'Edit products'             => 'Керування товаром',
];
