<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'add to cart'           => 'Добавить в корзину',
    'cart'                  => 'Корзина',
    'price'                 => 'Цена',
    'quantity'              => 'Количество',
    'delete'                => 'Удалить',
    'total price'           => 'Общая стоимость заказа',
    'make order'            => 'Оформить заказ',
    'order no'              => 'Заказ № ',
    'order success'         => 'Ваш заказ принят. Наш менеджер скоро с Вами свяжется.',
    'orders'                => 'Заказы',
    'status pending'        => 'В ожидании',
    'status in progress'    => 'В работе',
    'status ready'          => 'Готов',
    'status closed'         => 'Закрыт',
    'status'                => 'Статус',
    'open'                  => 'Открыть',
    'time'                  => 'Время заказа',
    'product name'          => 'Наименование Товара',
    'in cart'               => 'В корзине',

];
