<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'full name'                                                   => 'Full name',
    'email'                                                       => 'Email',
    'phone'                                                       => 'Phone number',
    'address'                                                     => 'Address',
    'save changes'                                                => 'Save changes',
    'sign in'                                                     => 'Sign in',
    'username'                                                    => 'Username',
    'password'                                                    => 'Password',
    'rememberMe'                                                  => 'Remember me',
    'login'                                                       => 'Login',
    'If you forgot your password you can'                         => 'If you forgot your password you can',
    'reset it'                                                    => 'reset it',
    'For new user you can'                                        => 'For new user you can',
    'sign up'                                                     => 'sign up',
    'Change Password'                                             => 'Change Password',
    'Please fill out the following fields to change password:'    => 'Please fill out the following fields to change password:',
    'old Password'                                                => 'Old Password',
    'new Password'                                                => 'New Password',
    'retype Password'                                             => 'Retype Password',
    'Change'                                                      => 'Change',
    'Request password reset'                                      => 'Request password reset',
    'Send'                                                        => 'Send',
    'Reset password'                                              => 'Reset password',
    'Save'                                                        => 'Save',
    'Please choose your new password:'                            => 'Please choose your new password:',
    'Create account'                                              => 'Create account',
    'Users'                                                       => 'Users',

];
