<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'add to cart'           => 'Додати в кошик',
    'cart'                  => 'Кошик',
    'price'                 => 'Ціна',
    'quantity'              => 'Кількість',
    'delete'                => 'Видалити',
    'total price'           => 'Загальна вартість замовлення',
    'make order'            => 'Оформити замовлення',
    'order no'              => 'Замовлення № ',
    'order success'         => 'Ваше замовлення прийнято. Наш менеджер скоро з Вами зв\'яжеться',
    'orders'                => 'Замовлення',
    'status pending'        => 'В очікуванні',
    'status in progress'    => 'В процесі',
    'status ready'          => 'Виконано',
    'status closed'         => 'Закрито',
    'status'                => 'Статус',
    'open'                  => 'Відкрити',
    'time'                  => 'Час замовлення',
    'product name'          => 'Найменування товару',
    'in cart'               => 'В кошику',
];
