<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'add to cart'           => 'Add to cart',
    'cart'                  => 'Cart',
    'price'                 => 'Price',
    'quantity'              => 'Quantity',
    'delete'                => 'Delete',
    'total price'           => 'Total order price',
    'make order'            => 'Make order',
    'order no'              => 'Order No. ',
    'order success'         => 'Your order is registered. Our manager will contact you soon.',
    'orders'                => 'Orders',
    'status pending'        => 'Pending',
    'status in progress'    => 'In progress',
    'status ready'          => 'Ready',
    'status closed'         => 'Closed',
    'status'                => 'Status',
    'open'                  => 'Open',
    'time'                  => 'Order time',
    'product name'          => 'Product name',
    'in cart'               => 'In cart',
];
